defaults:
  - _self_
  - model: null
  - model@teacher: null # if set, distillation is used
  - datamodule: h5


seed: 12345
used_gpus: null
checkpoint: ???

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  default_root_dir: null
  limit_val_batches: 1.0