defaults:
  - _self_
  - model: null


seed: 12345
used_gpus: null
batch_size: 10
out_path: ???
data_path: ???
qrels_path: ???

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  default_root_dir: null
  deterministic: True